@startuml Document (state machine)

skinparam state {
  BackgroundColor<<Pseudo>> White
}

state New: document was created in\n DMS Webapp
state ToBeVerified <<Pseudo>>: document needs to be\nchecked for completeness\nin DMS Webapp
state Incomplete: document lacks \nimportant data for\nusage in DMS Webapp
state Published: document content can be\nfound with normal search\nin DMS Webapp

state Failed <<Pseudo>>: document creation failed

state EndFailed <<end>>
state EndSuccess <<end>> 

[*] --> Failed: create document
note left of Failed: <b>pseudo status</b>:\n\nthis statuscannot\nbe saved in DMS\nwebapp since the\ninitial creation via\nAPI already failed 
Failed --> EndFailed

[*] --> New: create document
note right of New: document was\ncreated via API\n(with or w/out\nmeta data)
New --> ToBeVerified: upload document file
note right of ToBeVerified: <b>pseudo status</b>:\n\nthis status does not need to be saved\nin DMS webapp because the automatic\ncompleteness check after document\nupload will immediately move on to the\nsubsequent status "Published" or\n"Incomplete"
ToBeVerified --> Published: run completeness check
note right of Published: document has\npassed the\ncompleteness\ncheck
ToBeVerified --> Incomplete: run completeness check
note right of Incomplete: document has\nNOT passed the\ncompleteness\ncheck
Incomplete --> Published: supplement document data
Published --> EndSuccess

@enduml